apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: sqlbee
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: sqlbee
    svc: sqlbee