apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.webhook.name }}
  labels:
    app: sqlbee
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/name: {{ template "sqlbee.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
webhooks:
  - name: {{ .Values.service.name }}.{{ .Release.Namespace }}.svc
    clientConfig:
      service:
        name: {{ .Values.service.name }}
        namespace: {{ .Release.Namespace }}
        path: "/api/v1beta/mutate"
      caBundle: "{{ required "A valid ca bundle is required for the mutating webhook configuration" .Values.webhook.caBundle }}"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
{{ if .Values.webhook.namespaceSelector }}
    namespaceSelector:
{{ toYaml .Values.webhook.namespaceSelector | indent 7 }}
{{ end }}
