{{- $secretName := printf "%s-certs" (include "sqlbee.name" .) -}}

{{- $altNames := list ( printf "%s.%s" .Values.service.name .Release.Namespace ) ( printf "%s.%s.svc" .Values.service.name .Release.Namespace ) -}}
{{- $ca := genCA "sqlbee-ca" 3650 -}}
{{- $genCert := genSignedCert .Values.service.name nil $altNames 3650 $ca -}}
{{- $cert := $genCert.Cert | b64enc -}}
{{- $key := $genCert.Key | b64enc -}}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
{{- if $secret }}
  {{- $cert = index $secret.data "tls.crt" -}}
  {{- $key = index $secret.data "tls-key" -}}
{{- end -}}

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.webhook.name }}
  labels:
    app: sqlbee
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/name: {{ template "sqlbee.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
webhooks:
  - name: {{ .Values.service.name }}.{{ .Release.Namespace }}.svc
    clientConfig:
      service:
        name: {{ .Values.service.name }}
        namespace: {{ .Release.Namespace }}
        path: "/api/v1beta/mutate"
      caBundle: "{{ $cert }}"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
{{ if .Values.webhook.namespaceSelector }}
    namespaceSelector:
{{ toYaml .Values.webhook.namespaceSelector | indent 7 }}
{{ end }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ $secretName | quote }}
  labels:
    app: {{ template "sqlbee.name" . }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  tls.crt: {{ $cert }}
  tls.key: {{ $key }}
